[build]
  base = "/"
  publish = "frontend/dist"
  command = "bash ./netlify-build.sh"

[build.environment]
  NODE_VERSION = "20.18.0"
  SKIP_TYPESCRIPT_CHECK = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "#static"
  command = "node keep-server-running.js"
  port = 5173
  targetPort = 5173
  publish = "frontend/public"
  autoLaunch = true

# Edge Functions
[[edge_functions]]
  path = "/spotify/*"
  function = "spotify-api"

# Handle direct function request for testing deployment
[[redirects]]
  from = "/test"
  to = "/.netlify/functions/hello-world"
  status = 200
  force = true

# Handle environment test requests
[[redirects]]
  from = "/env-test"
  to = "/.netlify/functions/env-test"
  status = 200
  force = true

# Handle all other API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
