// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";
import { SuspenseWrapper } from "./components/SuspenseWrapper";

const AddSong = lazy(() => import("./pages/AddSong"));
const App = lazy(() => import("./pages/App"));
const CreateQueue = lazy(() => import("./pages/CreateQueue"));
const Dashboard = lazy(() => import("./pages/Dashboard"));
const ForgotPassword = lazy(() => import("./pages/ForgotPassword"));
const GuestQueueView = lazy(() => import("./pages/GuestQueueView"));
const JoinQueue = lazy(() => import("./pages/JoinQueue"));
const Login = lazy(() => import("./pages/Login"));
const Profile = lazy(() => import("./pages/Profile"));
const QueueView = lazy(() => import("./pages/QueueView"));
const ResetPassword = lazy(() => import("./pages/ResetPassword"));
const Setup = lazy(() => import("./pages/Setup"));
const Signup = lazy(() => import("./pages/Signup"));
const SignupConfirmation = lazy(() => import("./pages/SignupConfirmation"));
const SpotifyCallback = lazy(() => import("./pages/SpotifyCallback"));

export const userRoutes: RouteObject[] = [
	{ path: "/add-song", element: <SuspenseWrapper><AddSong /></SuspenseWrapper>},
	{ path: "/addsong", element: <SuspenseWrapper><AddSong /></SuspenseWrapper>},
	{ path: "/", element: <SuspenseWrapper><App /></SuspenseWrapper>},
	{ path: "/create-queue", element: <SuspenseWrapper><CreateQueue /></SuspenseWrapper>},
	{ path: "/createqueue", element: <SuspenseWrapper><CreateQueue /></SuspenseWrapper>},
	{ path: "/dashboard", element: <SuspenseWrapper><Dashboard /></SuspenseWrapper>},
	{ path: "/forgot-password", element: <SuspenseWrapper><ForgotPassword /></SuspenseWrapper>},
	{ path: "/forgotpassword", element: <SuspenseWrapper><ForgotPassword /></SuspenseWrapper>},
	{ path: "/guest-queue-view", element: <SuspenseWrapper><GuestQueueView /></SuspenseWrapper>},
	{ path: "/guestqueueview", element: <SuspenseWrapper><GuestQueueView /></SuspenseWrapper>},
	{ path: "/join-queue", element: <SuspenseWrapper><JoinQueue /></SuspenseWrapper>},
	{ path: "/joinqueue", element: <SuspenseWrapper><JoinQueue /></SuspenseWrapper>},
	{ path: "/login", element: <SuspenseWrapper><Login /></SuspenseWrapper>},
	{ path: "/profile", element: <SuspenseWrapper><Profile /></SuspenseWrapper>},
	{ path: "/queue-view", element: <SuspenseWrapper><QueueView /></SuspenseWrapper>},
	{ path: "/queueview", element: <SuspenseWrapper><QueueView /></SuspenseWrapper>},
	{ path: "/reset-password", element: <SuspenseWrapper><ResetPassword /></SuspenseWrapper>},
	{ path: "/resetpassword", element: <SuspenseWrapper><ResetPassword /></SuspenseWrapper>},
	{ path: "/setup", element: <SuspenseWrapper><Setup /></SuspenseWrapper>},
	{ path: "/signup", element: <SuspenseWrapper><Signup /></SuspenseWrapper>},
	{ path: "/signup-confirmation", element: <SuspenseWrapper><SignupConfirmation /></SuspenseWrapper>},
	{ path: "/signupconfirmation", element: <SuspenseWrapper><SignupConfirmation /></SuspenseWrapper>},
	{ path: "/spotify-callback", element: <SuspenseWrapper><SpotifyCallback /></SuspenseWrapper>},
	{ path: "/spotifycallback", element: <SuspenseWrapper><SpotifyCallback /></SuspenseWrapper>},
];
